<?php
/*
 ARCHIVO DE CONFIGURACION PHP DEL SISTEMA
ACA VAN LAS DIRECCIONES DEL SISTEMA (GENERALMENTE LOCALHOST)
EL NOMBRE DE USUARIO QUE USAREMOS PARA HABLAR CON EL DBMS,
EL PASSWORD DEL USUARIO
Y LA BASE DE DATOS CON LA QUE TRABAJAREMOS
*/

$direccion = "localhost";
$usuariobd = "root";
$passwd = "";//"transoceanica1q2w3e";
$basedatos = "totemMallPlazaPca";
?>
